export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MOBILE_NAV = 'SHOW_MOBILE_NAV';
export const HIDE_MOBILE_NAV = 'HIDE_MOBILE_NAV';
export const SHOW_DAILY_MODAL = 'SHOW_DAILY_MODAL';
export const SHOW_SETTINGS_MODAL = 'SHOW_SETTINGS_MODAL';
export const HIDE_SETTINGS_MODAL = 'HIDE_SETTINGS_MODAL';
export const SHOW_DAILY_EDIT_MODAL = 'SHOW_DAILY_EDIT_MODAL';
export const HIDE_DAILY_EDIT_MODAL = 'HIDE_DAILY_EDIT_MODAL';
export const GET_INTAKE = 'GET_INTAKE';
export const GET_UID = 'GET_UID';
export const GET_MEALS = 'GET_MEALS';
export const GET_TOTAL_KCAL = 'GET_TOTAL_KCAL';

export const GET_START_DAY = 'GET_START_DAY';
export const GET_START_MONTH = 'GET_START_MONTH';
export const GET_START_YEAR = 'GET_START_YEAR';

export const GET_END_DAY = 'GET_END_DAY';
export const GET_END_MONTH = 'GET_END_MONTH';
export const GET_END_YEAR = 'GET_END_YEAR';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const LOGOUT = 'LOGOUT';